name: medicos
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+12

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: 3.4.1
  cupertino_icons: 1.0.8
  device_info_plus: 12.2.0
  encrypt: 5.0.3
  file_picker: ^10.3.3
  firebase_core: 4.2.0
  firebase_database: 12.0.3
  flex_color_scheme: 8.3.1
  flutter:
    sdk: flutter
  flutter_cache_manager: 3.4.1
  flutter_flavorizr: 2.4.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: 2.2.1
  geolocator: ^14.0.1
  get: 4.7.2
  get_storage: ^2.1.1
  google_maps_flutter: ^2.14.0
  http: 1.5.0
  intl: 0.20.2
  local_auth: 2.3.0
  logger: ^2.6.2
  package_info_plus: 9.0.0
  path_provider: 2.1.5
  pdfrx: 2.2.8
  share_plus: 12.0.1
  url_launcher: 6.3.2

dev_dependencies:
  args: ^2.7.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
